name    'puppet-langs'
version '0.1.0'
source 'git@github.com:narkisr/puppet-langs.git'
author 'narkisr'
license 'Apache-V2'
summary 'This module sets up common programming languages '
description 'This module sets up common programming languages like Ruby, Erlang, Coffeescript'
project_page 'https://github.com/narkisr/puppet-langs'

dependency 'puppetlabs/apt', '>= 1.1.0'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
